/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author Sebastian Cespedes Rodas
 */
public class Calculadora extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(Calculadora.class.getName());

    private Lexer.Cinta cinta;
    private Lexer.Analex analex;
    private Lexer.Parser parser;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        cinta = new Lexer.Cinta("");
        analex = new Lexer.Analex(cinta);
        parser = new Lexer.Parser(analex);
        actualizarTSVAR();
    }

    private void actualizarTSVAR() {
        jLabelTSVAR.setText(analex.getTS().toHtmlTable());
    }

    private void insertar(String texto) {
        jTextArea1.append(texto);
        jTextArea1.requestFocus();
    }

    private void calcular() {
        try {
            String expresion = jTextArea1.getText().trim();

            if (expresion.isEmpty()) {
                jTextArea2.setText("");
                actualizarTSVAR();
                return;
            }

            cinta.init(expresion);
            analex.init();

            float resultado = parser.ejecutar();

            jTextArea2.setText(String.valueOf(resultado));
            actualizarTSVAR();

        } catch (Exception e) {
            jTextArea2.setText("Error: " + e.getMessage());
            actualizarTSVAR();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonPA = new javax.swing.JButton();
        jButtonPC = new javax.swing.JButton();
        jButtonMAS = new javax.swing.JButton();
        jButtonMENOS = new javax.swing.JButton();
        jButtonPOR = new javax.swing.JButton();
        jButtonDIV = new javax.swing.JButton();
        jButtonASSIGN = new javax.swing.JButton();
        jButtonCVAL = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonMOD = new javax.swing.JButton();
        jButtonPUNTO = new javax.swing.JButton();
        jLabelTSVAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jTextArea2.setRows(1);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jTextArea1.setRows(1);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton0.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.setBorderPainted(false);
        jButton0.addActionListener(this::jButton0ActionPerformed);

        jButton6.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton8.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton9.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(this::jButton9ActionPerformed);

        jButtonPA.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonPA.setText("(");
        jButtonPA.setBorderPainted(false);
        jButtonPA.addActionListener(this::jButtonPAActionPerformed);

        jButtonPC.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonPC.setText(")");
        jButtonPC.setBorderPainted(false);
        jButtonPC.addActionListener(this::jButtonPCActionPerformed);

        jButtonMAS.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonMAS.setText("+");
        jButtonMAS.setBorderPainted(false);
        jButtonMAS.addActionListener(this::jButtonMASActionPerformed);

        jButtonMENOS.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonMENOS.setText("-");
        jButtonMENOS.setBorderPainted(false);
        jButtonMENOS.addActionListener(this::jButtonMENOSActionPerformed);

        jButtonPOR.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonPOR.setText("*");
        jButtonPOR.setBorderPainted(false);
        jButtonPOR.addActionListener(this::jButtonPORActionPerformed);

        jButtonDIV.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonDIV.setText("/");
        jButtonDIV.setBorderPainted(false);
        jButtonDIV.addActionListener(this::jButtonDIVActionPerformed);

        jButtonASSIGN.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonASSIGN.setText("->");
        jButtonASSIGN.setBorderPainted(false);
        jButtonASSIGN.addActionListener(this::jButtonASSIGNActionPerformed);

        jButtonCVAL.setBackground(new java.awt.Color(153, 255, 153));
        jButtonCVAL.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonCVAL.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCVAL.setText("CVAL");
        jButtonCVAL.setBorderPainted(false);
        jButtonCVAL.addActionListener(this::jButtonCVALActionPerformed);

        jButtonC.setBackground(new java.awt.Color(255, 153, 153));
        jButtonC.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonC.setForeground(new java.awt.Color(0, 0, 0));
        jButtonC.setText("C");
        jButtonC.setBorderPainted(false);
        jButtonC.addActionListener(this::jButtonCActionPerformed);

        jButtonMOD.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonMOD.setText("%");
        jButtonMOD.setBorderPainted(false);
        jButtonMOD.addActionListener(this::jButtonMODActionPerformed);

        jButtonPUNTO.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        jButtonPUNTO.setText(".");
        jButtonPUNTO.setBorderPainted(false);
        jButtonPUNTO.addActionListener(this::jButtonPUNTOActionPerformed);

        jLabelTSVAR.setText("TSVAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonPA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonPC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonPOR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonCVAL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonASSIGN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMENOS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(jLabelTSVAR)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMENOS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonPOR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCVAL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonASSIGN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabelTSVAR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        insertar("0");
    }// GEN-LAST:event_jButton0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        insertar("1");
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        insertar("2");
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        insertar("3");
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        insertar("4");
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        insertar("5");
    }// GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        insertar("6");
    }// GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        insertar("7");
    }// GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        insertar("8");
    }// GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        insertar("9");
    }// GEN-LAST:event_jButton9ActionPerformed

    private void jButtonPAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPAActionPerformed
        // TODO add your handling code here:
        insertar("(");
    }// GEN-LAST:event_jButtonPAActionPerformed

    private void jButtonPCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPCActionPerformed
        // TODO add your handling code here:
        insertar(")");
    }// GEN-LAST:event_jButtonPCActionPerformed

    private void jButtonMASActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonMASActionPerformed
        // TODO add your handling code here:
        insertar("+");
    }// GEN-LAST:event_jButtonMASActionPerformed

    private void jButtonMENOSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonMENOSActionPerformed
        // TODO add your handling code here:
        insertar("-");
    }// GEN-LAST:event_jButtonMENOSActionPerformed

    private void jButtonPORActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPORActionPerformed
        // TODO add your handling code here:
        insertar("*");
    }// GEN-LAST:event_jButtonPORActionPerformed

    private void jButtonDIVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDIVActionPerformed
        // TODO add your handling code here:
        insertar("/");
    }// GEN-LAST:event_jButtonDIVActionPerformed

    private void jButtonASSIGNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonASSIGNActionPerformed
        // TODO add your handling code here:
        insertar("->");
    }// GEN-LAST:event_jButtonASSIGNActionPerformed

    private void jButtonCVALActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCVALActionPerformed
        // TODO add your handling code here:
        calcular();
    }// GEN-LAST:event_jButtonCVALActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextArea2.setText("");
    }// GEN-LAST:event_jButtonCActionPerformed

    private void jButtonMODActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonMODActionPerformed
        // TODO add your handling code here:
        insertar("%");
    }// GEN-LAST:event_jButtonMODActionPerformed

    private void jButtonPUNTOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPUNTOActionPerformed
        // TODO add your handling code here:
        insertar(".");
    }// GEN-LAST:event_jButtonPUNTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonASSIGN;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCVAL;
    private javax.swing.JButton jButtonDIV;
    private javax.swing.JButton jButtonMAS;
    private javax.swing.JButton jButtonMENOS;
    private javax.swing.JButton jButtonMOD;
    private javax.swing.JButton jButtonPA;
    private javax.swing.JButton jButtonPC;
    private javax.swing.JButton jButtonPOR;
    private javax.swing.JButton jButtonPUNTO;
    private javax.swing.JLabel jLabelTSVAR;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
